os: Visual Studio 2015
version: '{build}'
build: off
platform: x64
environment:
  matrix:
    - nodejs_version: 12
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm i -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm i
matrix:
  fast_finish: true
shallow_clone: true
clone_depth: 1
test_script: npm t
cache:
  - node_modules
